# Stellar Token Metadata Dosyası

VERSION="2.0"

# İletişim Bilgileri
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://yourdomain.com/federation"
AUTH_SERVER="https://yourdomain.com/auth"
TRANSFER_SERVER="https://yourdomain.com/transfer"
SIGNING_KEY="GAEXAMPLEPUBLICKEY"

# Token Bilgileri
[[CURRENCIES]]
code="TurkCoinn"
issuer="GCAI4LK7Y4WKXM4P6FCNSRXZCX7AX66C3QE47NLZXBSWCKR2F3362APA"
status="live"
display_decimals=7
anchor_asset_type="crypto"
